require 'vcloud/fog'

require 'vcloud/core/entity'
require 'vcloud/core/metadata_helper'
require 'vcloud/core/compute_metadata'
require 'vcloud/core/vdc'
require 'vcloud/core/edge_gateway'
require 'vcloud/core/vm'
require 'vcloud/core/vapp'
require 'vcloud/core/vapp_template'
require 'vcloud/core/org_vdc_network'
