#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'erb'
require 'fog'
require 'open3'
require 'pp'
require 'vcloud'

# delete a vApp by name or id
# NB: This will only work on Stopped (aka undeployed) vApps at present
#     Potentially we could add a --force option to also do
#     a shutdown/stop/undeploy operation additionally, so we can delete running
#     vApps.

vapp_name_or_id = ARGV.shift

if vapp_name_or_id =~ /^vapp-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/
  # id
  vapp = Vcloud::Core::Vapp.new(vapp_name_or_id)
else
  # name
  vapp = Vcloud::Core::Vapp.get_by_name(vapp_name_or_id)
end

puts "Deleting vApp #{vapp.name} (#{vapp.id})"
Vcloud::Fog::ServiceInterface.new.delete_vapp(vapp.id)

