#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'pp'
require 'vcloud'
require 'methadone'

ENV['FOG_MOCK'] && Fog.mock!

class App

  include Methadone::Main
  include Methadone::CLILogging

  main do

    fsi = Vcloud::FogServiceInterface.new()
    token = fsi.vcloud_token
    end_point = fsi.end_point

    rel_url = ARGV.shift
    url = end_point + rel_url

    system("/usr/bin/curl -H 'Accept:#{options[:content_type]}' -H 'x-vcloud-authorization: #{token}' #{ARGV.join(' ')} #{url}")

  end

  options[:content_type] = "application/*+xml;version=5.1"

  on("--content_type", "=ATTRIBUTE",
     "Override default content_type (#{options[:content_type]})" ) do |v|
    options[:content_type] = v
  end

  on("--verbose", "Verbose output")
  on("--debug",   "Debugging output")
  
  arg :relative_url, :optional

  description '
  vcloud-curl takes a relative URL for a query (to the base api url), then
  shells out to cURL with the remainder of ARGV

  See https://github.com/alphagov/vcloud-tools for more info'

  version Vcloud::VERSION

  go!
end


