#!/bin/sh

usage() {
  echo "vcloud-curl: simple curl wrapper to allow GET requests to vcloud API"
  echo
  echo "Usage:"
  echo "  vcloud-curl {request}"
  echo 
  echo "where {request} is the resource required after the /api part of the url"
  echo "eg: vcloud-curl vApp/{vm-id}/virtualHardwareSection/cpu"
  echo 
  echo "You must set in environment:"
  echo "  VCLOUD_HOST"
  echo "  VCLOUD_ORG"
  echo "  VCLOUD_USER"
  echo "  VCLOUD_PASS"
  exit 1
}

[ -z "$VCLOUD_HOST" ] && usage
[ -z "$VCLOUD_ORG" ]  && usage
[ -z "$VCLOUD_USER" ] && usage
[ -z "$VCLOUD_PASS" ] && usage

CURL_OPTS="-k -s"

SESSION_KEY=`curl -i $CURL_OPTS \
   -H 'Accept:application/*+xml;version=1.5' \
   -u "${VCLOUD_USER}@${VCLOUD_ORG}:${VCLOUD_PASS}" \
   -X POST \
   "https://${VCLOUD_HOST}/api/sessions" \
   | grep '^x-vcloud-authorization:' \
   | tr -d '\r' \
   | awk '{print $2}'
   `

if [ -z "${SESSION_KEY}" ]; then
  echo "Failed to get vCloud session. Bailing"
  exit 2
fi

curl $CURL_OPTS \
   -H 'Accept:application/*+xml;version=1.5' \
   -H "x-vcloud-authorization: ${SESSION_KEY}" \
   "https://${VCLOUD_HOST}/api/$1"

# Log out -- fails with 401
#curl $CURL_OPTS \
#   -H 'Accept:application/*+xml;version=1.5' \
#   -H "x-vcloud-authorization: ${SESSION_KEY}" \
#   -X DELETE \
#   "https://${VCLOUD_HOST}/api/sessions"

